name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [frontend, backend] # Run CI for both folders

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ matrix.folder }}/.npm
          key: ${{ runner.os }}-${{ matrix.folder }}-${{ hashFiles(format('{0}/package-lock.json', matrix.folder)) }}

      - name: Install dependencies
        working-directory: ${{ matrix.folder }}
        run: npm ci

      - name: Run tests (if any)
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -f "package.json" ] && npm run | grep -q "test"; then
            npm test
          else
            echo "ℹ️ No test script defined in ${{ matrix.folder }}"
          fi

      - name: Run lint (if defined)
        working-directory: ${{ matrix.folder }}
        run: |
          if npm run | grep -q "lint"; then
            echo "✅ Found lint script in ${{ matrix.folder }}. Running lint..."
            npm run lint
          else
            echo "ℹ️ No lint script defined in ${{ matrix.folder }}"
          fi

      - name: Run build (if defined)
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -f "package.json" ] && npm run | grep -q "build"; then
            echo "🛠️ Running build script in ${{ matrix.folder }}"
            npm run build
          else
            echo "ℹ️ No build script defined in ${{ matrix.folder }}"
          fi